status = error
name = PySpark

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yy/MM/dd HH:mm:ss} %p %c{1}: %m%n

rootLogger.level = warn
rootLogger.appenderRef.console.ref = console

logger.NativeCodeLoader.name = org.apache.hadoop.util.NativeCodeLoader
logger.NativeCodeLoader.level = off

logger.NetUtils.name = org.apache.logging.log4j.core.util.NetUtils
logger.NetUtils.level = off

logger.MacAddressUtil.name = org.apache.spark.util.MacAddressUtil
logger.MacAddressUtil.level = off
